### ISSUE TITLE
Failing to start minio service on centos 6.9

### ISSUE THREAD

**Issue by Mo33n** [minio/minio-service#8] opened 2017-09-07 16:40 UTC
i have followed the following link,
https://github.com/minio/minio-service/tree/master/linux-sysvinit

but fail to start the service .

[root@ivr ~]# service minio start
which: no minio in (/sbin:/usr/sbin:/bin:/usr/bin)
Starting minio
usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
start-stop-daemon: unrecognized option '--config-dir'
Try `start-stop-daemon --help' for more information.

**Comment by Mo33n** [comment] 2017-09-12 08:12
any luck ?

**Comment by Mo33n** [comment] 2017-10-17 09:22
any update guys ?

**Comment by harshavardhana** [comment] 2017-10-17 09:30
Not sure what is going wrong here @Mo33n we do not have any CentOS 6.9 instances available. Can you provide us more information?  it is perhaps better for you to try out `systemctl` instead ? https://github.com/minio/minio-service/tree/master/linux-systemd

**Comment by Mo33n** [comment] 2017-10-17 09:50
i found the problem , there was not minio file in /usr/bin so i copied it from /usr/local/bin

Now its shows no error, But stil dont start the minio.,


[root@ivr /]# service minio start
Starting minio
[root@ivr /]# ps -ef | grep minio
root     29555 26915  0 12:48 pts/4    00:00:00 grep minio
[root@ivr /]#

**Comment by harshavardhana** [comment] 2017-12-10 10:57
Closing this as working as intended, please re-open if the issue persists.

**Closed by harshavardhana** 2017-12-10 10:57 UTC
